name: Deploy Storybook

on:
  push:
    branches: [master]

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: cd ./SQFormDocs
      - run: npm ci
      - run: cd ..
      - run: npm ci
      - run: npm run build-storybook
      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build-storybook
